#!/usr/bin/env bash
# Print an llvm-config whose --bindir contains both clang and ld.lld.
#
# prospero-clang resolves its real compiler and linker through
# llvm-config --bindir. That is fine when one package ships all three, but on
# Nix (and some distros) clang, lld and the llvm tools are separate store
# outputs, so the bindir llvm-config reports holds no clang and every build
# dies with "No such file or directory". This assembles a shim bindir in that
# case and prints an llvm-config pointing at it.
#
# Prints nothing if no working bindir can be found; the build then fails with
# the toolchain's own error, which is clearer than a bad guess.
set -uo pipefail

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/pweb5-llvm/bin"
REAL_CONFIG="${LLVM_CONFIG:-$(command -v llvm-config 2>/dev/null)}"

# Every finder below must print a *directory*, never a binary path.
have_both() { [ -n "${1:-}" ] && [ -x "$1/clang" ] && [ -x "$1/ld.lld" ]; }

# 1. Whatever llvm-config already on PATH reports.
if [ -n "$REAL_CONFIG" ]; then
  bindir="$("$REAL_CONFIG" --bindir 2>/dev/null)"
  if have_both "$bindir"; then
    echo "$REAL_CONFIG"
    exit 0
  fi
fi

# 2. Assemble one. Prefer the real clang package over a distro wrapper, which
#    may inject its own flags; PATH is the last resort.
clang_dir() {
  local d b
  for d in /nix/store/*-clang-[0-9]*/bin /usr/lib/llvm-*/bin /usr/bin; do
    [ -x "$d/clang" ] && { echo "$d"; return; }
  done
  b="$(command -v clang 2>/dev/null)"
  [ -n "$b" ] && dirname "$b"
}

lld_dir() {
  local d b
  for d in /nix/store/*-lld-[0-9]*/bin /usr/lib/llvm-*/bin /usr/bin; do
    [ -x "$d/ld.lld" ] && { echo "$d"; return; }
  done
  b="$(command -v ld.lld 2>/dev/null)"
  [ -n "$b" ] && dirname "$b"
}

llvm_dir() {
  local d b
  for d in /nix/store/*-llvm-[0-9]*/bin /usr/lib/llvm-*/bin; do
    [ -x "$d/llvm-ar" ] && { echo "$d"; return; }
  done
  b="$(command -v llvm-ar 2>/dev/null)"
  [ -n "$b" ] && dirname "$b"
}

CLANG_DIR="$(clang_dir)"
LLD_DIR="$(lld_dir)"
[ -n "$CLANG_DIR" ] && [ -n "$LLD_DIR" ] || exit 0

rm -rf "$CACHE"
mkdir -p "$CACHE" || exit 0

# Front ends from the clang package; linker and llvm-* tools from wherever
# they happen to live.
for t in clang clang++ clang-cpp clang-21 clang-22; do
  [ -e "$CLANG_DIR/$t" ] && ln -sf "$CLANG_DIR/$t" "$CACHE/$t"
done
for d in "$LLD_DIR" "$(llvm_dir)"; do
  [ -d "$d" ] || continue
  for t in "$d"/ld.lld "$d"/lld "$d"/llvm-*; do
    [ -e "$t" ] && ln -sf "$t" "$CACHE/$(basename "$t")"
  done
done

[ -x "$CACHE/clang" ] && [ -x "$CACHE/ld.lld" ] || exit 0

cat > "$CACHE/llvm-config" <<EOF
#!/usr/bin/env bash
# Generated by pWeb5 dispatcher/llvm-shim.sh - reports a bindir holding both
# clang and ld.lld. Everything else is delegated to the real llvm-config.
case "\${1:-}" in
  --bindir) echo "$CACHE" ;;
  *) exec ${REAL_CONFIG:-llvm-config} "\$@" ;;
esac
EOF
chmod +x "$CACHE/llvm-config"

echo "$CACHE/llvm-config"
